//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicableDiseaseSiteModality
    {
        public int ApplicableDiseaseSiteModalityID { get; set; }
        public int DiseaseSiteID { get; set; }
        public Nullable<int> ModalityID { get; set; }
    }
}
