//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2018_MPFS_Addendum_B
    {
        public int Id { get; set; }
        public string CPT1__HCPCS { get; set; }
        public string Mod { get; set; }
        public string Status { get; set; }
        public string Not_Used_for_Medicare_Payment { get; set; }
        public string Description { get; set; }
        public string Work_RVUs2 { get; set; }
        public string Non_Facility_PE_RVUs2 { get; set; }
        public string Facility_PE_RVUs2 { get; set; }
        public string Mal_Practice_RVUs2 { get; set; }
        public string Total_Non_Facility_RVUs2 { get; set; }
        public string Total_Facility_RVUs2 { get; set; }
        public string Global { get; set; }
    }
}
