//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2018_OPPS_Addendum_B
    {
        public int Id { get; set; }
        public string HCPCS_Code { get; set; }
        public string Short_Descriptor { get; set; }
        public string CI { get; set; }
        public string SI { get; set; }
        public string APC_ { get; set; }
        public Nullable<double> Relative_Weight { get; set; }
        public Nullable<decimal> Payment_Rate_ { get; set; }
        public string National_Unadjusted_Copayment_ { get; set; }
        public string Minimum_Unadjusted_Copayment_ { get; set; }
    }
}
