//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2018_GPCI_Addendum_E
    {
        public string MedAdmin { get; set; }
        public Nullable<double> LocalNumber { get; set; }
        public string LocalName { get; set; }
        public Nullable<double> PW_GPCI { get; set; }
        public Nullable<double> PE_GPCI { get; set; }
        public Nullable<double> MP_GPCI { get; set; }
        public int Id { get; set; }
    }
}
