//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCI_Edits
    {
        public int CCI_Edit_ID { get; set; }
        public string Column_1 { get; set; }
        public string Column_2 { get; set; }
        public string C__in_existence { get; set; }
        public string Effective_Date { get; set; }
        public string Deletion { get; set; }
        public string Modifier { get; set; }
        public string PTP_Edit_Rationale { get; set; }
    }
}
