//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Wage_Index
    {
        public int Id { get; set; }
        public string CBSA { get; set; }
        public string Area_Name { get; set; }
        public string State { get; set; }
        public string State_Code { get; set; }
        public string C2FY_2017_Average_Hourly_Wage { get; set; }
        public string C23_Year_Average_Hourly_Wage__2015_2016_2017_ { get; set; }
        public string Wage_Index { get; set; }
        public string GAF { get; set; }
        public string Reclassified_Wage_Index { get; set; }
        public string Reclassified_GAF { get; set; }
        public string C3Pre_Frontier_and_or_Pre_Rural_Floor_Wage_Index { get; set; }
        public string Eligible_for_Frontier_Wage_Index { get; set; }
        public string C4Eligible_for_Rural_Floor_Wage_Index { get; set; }
    }
}
