//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disease
    {
        public string Name { get; set; }
        public string CODE { get; set; }
        public string CATEGORY { get; set; }
        public string ACTIVE { get; set; }
        public string MODEL { get; set; }
        public string ID { get; set; }
    }
}
