//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3003E_emedicodesEntities : DbContext
    {
        public DB_A3003E_emedicodesEntities()
            : base("name=DB_A3003E_emedicodesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicableDiseaseSiteModality> ApplicableDiseaseSiteModalities { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<CaseCode> CaseCodes { get; set; }
        public virtual DbSet<CCI_Edits> CCI_Edits { get; set; }
        public virtual DbSet<CMS_Wage_Index> CMS_Wage_Index { get; set; }
        public virtual DbSet<disease> diseases { get; set; }
        public virtual DbSet<DiseaseSite> DiseaseSites { get; set; }
        public virtual DbSet<GPCI2017> GPCI2017 { get; set; }
        public virtual DbSet<HospitalTreatmentCode> HospitalTreatmentCodes { get; set; }
        public virtual DbSet<Modality> Modalities { get; set; }
        public virtual DbSet<MPFS_Addendum_B> MPFS_Addendum_B { get; set; }
        public virtual DbSet<MUE_Information> MUE_Information { get; set; }
        public virtual DbSet<OPPS_Addendum_B> OPPS_Addendum_B { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserAction> UserActions { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<C2018_MPFS_Addendum_B> C2018_MPFS_Addendum_B { get; set; }
        public virtual DbSet<C2018_OPPS_Addendum_B> C2018_OPPS_Addendum_B { get; set; }
        public virtual DbSet<C2018_GPCI_Addendum_E> C2018_GPCI_Addendum_E { get; set; }
    }
}
