//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPCI2017
    {
        public int GPCI_ID { get; set; }
        public string Carrier { get; set; }
        public string Locality_Number { get; set; }
        public string Locality_Name { get; set; }
        public string PW_GPCI { get; set; }
        public string PE_GPCI { get; set; }
        public string MP_GPCI { get; set; }
    }
}
