//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPFS_Addendum_B
    {
        public int MPFS_ID { get; set; }
        public string CPT1 { get; set; }
        public string CPT1_HCPCS { get; set; }
        public string Mod { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string Work_RVUs { get; set; }
        public string Non__Facility_PE_RVUs { get; set; }
        public string Facility_PE_RVUs { get; set; }
        public string Mal__Practice_RVUs { get; set; }
        public string Total_Non_Facility_RVUs { get; set; }
        public string Total_Facility_RVUs { get; set; }
        public string Global { get; set; }
    }
}
