//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUE_Information
    {
        public int MUE_ID { get; set; }
        public string HCPCS_CPT_Code { get; set; }
        public string Outpatient_Hospital_Services_MUE_Values { get; set; }
        public string MUE_Adjudication_Indicator { get; set; }
        public string MUE_Rationale { get; set; }
    }
}
