//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmediCodesWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAction
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string UserAction1 { get; set; }
        public Nullable<bool> IsSecureAction { get; set; }
    }
}
